# name
name: StratoLogger Documentation

# description
description: How to program, and field-program, a PerfectFlite StratoLogger.

# site theme
theme: jekyll-theme-minimal

# author
author: UND-ARC
author_email: mishaturnbull@gmail.com

show_downloads: true
